development:
  backend:
    host: 'localhost'
    port: 3000
    protocol: 'http'
  frontend:
    host: 'localhost'
    port: 8080
    protocol: 'http'

production:
  backend:
    host: 'library-tut-backend.herokuapp.com'
    protocol: 'https'
  frontend:
    host: 'library-tut.herokuapp.com'
    protocol: 'https'

test:
  backend:
    host: 'localhost'
    port: 3000
    protocol: 'http'
  frontend:
    host: 'localhost'
    port: 8080
    protocol: 'http'
